@ECHO OFF
cd C:\RPA\SAC\PROCESOS-PANEL\CORREGIR-CENTRO-CASOS\PYTHON
C:/Users/robotrocket2/AppData/Local/Programs/Python/Python39/python.exe C:\RPA\SAC\PROCESOS-PANEL\CORREGIR-CENTRO-CASOS\PYTHON\main.py
@ECHO ON